export const CODE_SAMPLES: Record<string, string> = {
  python: [
    'import requests',
    '',
    'API_KEY = "cpk_live_..."',
    'BASE_URL = "https://api.copypro.vn/v1"',
    '',
    'def generate_copy(industry, copy_type, product_name, tone="professional"):',
    '    response = requests.post(',
    '        f"{BASE_URL}/generate",',
    '        headers={"Authorization": f"Bearer {API_KEY}"},',
    '        json={',
    '            "industry": industry,',
    '            "type": copy_type,',
    '            "product_name": product_name,',
    '            "tone": tone,',
    '            "language": "vi"',
    '        }',
    '    )',
    '    response.raise_for_status()',
    '    return response.json()',
  ].join('\n'),

  javascript: [
    "const axios = require('axios');",
    '',
    'const API_KEY = process.env.COPYPRO_API_KEY;',
    "const BASE_URL = 'https://api.copypro.vn/v1';",
    '',
    'async function generateCopy({ industry, type, productName, tone = \'professional\' }) {',
    '  const { data } = await axios.post(`${BASE_URL}/generate`, {',
    '    industry,',
    '    type,',
    '    product_name: productName,',
    '    tone,',
    "    language: 'vi',",
    '  }, {',
    '    headers: { Authorization: `Bearer ${API_KEY}` }',
    '  });',
    '  return data;',
    '}',
  ].join('\n'),

  curl: [
    'curl -X POST https://api.copypro.vn/v1/generate \\',
    '  -H "Authorization: Bearer cpk_live_..." \\',
    '  -H "Content-Type: application/json" \\',
    "  -d '{",
    '    "industry": "ecommerce",',
    '    "type": "headline",',
    '    "product_name": "Ao thun cotton premium",',
    '    "tone": "urgent",',
    '    "language": "vi"',
    "  }'",
  ].join('\n'),

  php: [
    '<?php',
    "$apiKey = getenv('COPYPRO_API_KEY');",
    "$baseUrl = 'https://api.copypro.vn/v1';",
    '',
    '$payload = json_encode([',
    "    'industry' => 'ecommerce',",
    "    'type' => 'headline',",
    "    'product_name' => 'Ao thun cotton premium',",
    "    'tone' => 'urgent',",
    "    'language' => 'vi',",
    ']);',
    '',
    '$ch = curl_init("$baseUrl/generate");',
    'curl_setopt_array($ch, [',
    '    CURLOPT_RETURNTRANSFER => true,',
    '    CURLOPT_POST => true,',
    '    CURLOPT_HTTPHEADER => [',
    '        "Authorization: Bearer $apiKey",',
    "        'Content-Type: application/json',",
    '    ],',
    '    CURLOPT_POSTFIELDS => $payload,',
    ']);',
    '',
    '$response = curl_exec($ch);',
    'curl_close($ch);',
    'echo $response;',
  ].join('\n'),
};
